### ISSUE TITLE
Use database in application

### ISSUE THREAD

**Issue by quaster** [quaster/proz-chat#15]

**Comment by quaster** [comment]
### Register

- [ ] Add "Register" button

- [ ] Add "Password field"

- [ ] Send new message's type (REGISTER=8) with parameters (username, password)

- [ ] When server gets (REGISTER=8) we should check run Database.register(), and check if registration succeeded. Send appropriate message to Client (SUCCESS - 200 OK, FAIL - 486 BUSY_HERE).

- [ ] Client after sending REGISTER=8, waits for the response from server, if registration failed - show appropriate statement to user ("Username already exists").

### Login

- [ ] Send message (LOGIN=1) with parameters (username, password)

- [ ] Server check if username & pass are correct. Run Database.login(). Send appropriate response. (SUCCESS - LOGIN_SUCCESS = 6, FAIL - LOGIN_FAIL = 7)

- [ ] Client after login waits for the response, and shows statements to user.

### Send message

- [ ] Server after receiving message, should put message to database.

### Show history

- [ ] Create button "Show history"

- [ ] Send message SHOW_HISTORY = 9

- [ ] Server should handle this type of message, with Database.showHistory(String userOne, String userTwo). This method returns ArrayList of MessageTable.SingleMessage. Class Message should keep ArrayList<MessageTable.SingleMessage>, and client should retrieve data properly and send it to GUI.

**Comment by quaster** [comment]
Added new messages' types.

**Comment by vic3k515** [comment]
Added register button and password field
